name: Python Package using Conda

on:
    [push]
#   schedule:
#     - cron: "39 11 * * *"
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip3 install selenium==3.8.0
        pip3 install numpy
        conda install opencv
        pip install opencv
        pip3 install Pillow
        pip3 install matplotlib
    - name: generate config.ini
      run:
        python3 actions.py -u ${{ secrets.STUDENTNUM }} -p ${{ secrets.PASSWD }}
    - name: main
      run:
        python3 main.py
